In [1]:
# Q2
import numpy as np
import sympy as sp
np.random.seed(62)

A = np.random.randint(0, 10, size=(5, 5))
print("Matrix : A")
sp.Matrix(A)

Matrix : A


Matrix([
[2, 8, 1, 9, 3],
[5, 1, 4, 5, 1],
[9, 8, 3, 5, 1],
[0, 3, 5, 8, 0],
[1, 1, 1, 9, 3]])

In [2]:
A=np.array([[2, 8, 1, 9, 3], [5, 1, 4, 5 ,1], [9 ,8, 3, 5, 1], [0, 3, 5, 8 ,0], [1 ,1 ,1 ,9, 3]])

In [3]:
A[0]=A[0]/2
A[0]

array([1, 4, 0, 4, 1])

In [4]:
A[1]=5*A[0]-A[1]
A[1]

array([ 0, 19, -4, 15,  4])

In [5]:
A[2]=9*A[0]-A[2]
A[2]

array([ 0, 28, -3, 31,  8])

In [6]:
A[4]=A[4]-A[0]
A[4]

array([ 0, -3,  1,  5,  2])

In [7]:
A

array([[ 1,  4,  0,  4,  1],
       [ 0, 19, -4, 15,  4],
       [ 0, 28, -3, 31,  8],
       [ 0,  3,  5,  8,  0],
       [ 0, -3,  1,  5,  2]])

In [8]:
A[1]=A[1]/19
A[1]

array([0, 1, 0, 0, 0])

In [9]:
A[2]=28*A[1]-A[2]
A[2]

array([  0,   0,   3, -31,  -8])

In [10]:
A[3]=3*A[1]-A[3]
A[3]

array([ 0,  0, -5, -8,  0])

In [11]:
A[4]=(-3)*A[1]-A[4]
A[4]

array([ 0,  0, -1, -5, -2])

In [12]:
sp.Matrix(A)

Matrix([
[1, 4,  0,   4,  1],
[0, 1,  0,   0,  0],
[0, 0,  3, -31, -8],
[0, 0, -5,  -8,  0],
[0, 0, -1,  -5, -2]])

In [13]:
A[2]=A[2]/3
A[2]

array([  0,   0,   1, -10,  -2])

In [14]:
A[3]=A[3]+5*A[2]
A[3]

array([  0,   0,   0, -58, -10])

In [15]:
A[4]=A[2]+A[4]
A[4]

array([  0,   0,   0, -15,  -4])

In [16]:
sp.Matrix(A)

Matrix([
[1, 4, 0,   4,   1],
[0, 1, 0,   0,   0],
[0, 0, 1, -10,  -2],
[0, 0, 0, -58, -10],
[0, 0, 0, -15,  -4]])

In [17]:
A[3]=A[3]/-58
A[3]

array([0, 0, 0, 1, 0])

In [18]:
A[4]=A[4]+15*A[3]
A[4]

array([ 0,  0,  0,  0, -4])

In [19]:
sp.Matrix(A)

Matrix([
[1, 4, 0,   4,  1],
[0, 1, 0,   0,  0],
[0, 0, 1, -10, -2],
[0, 0, 0,   1,  0],
[0, 0, 0,   0, -4]])

In [20]:
A[4]=A[4]/-4
A[4]

array([0, 0, 0, 0, 1])

In [21]:
sp.Matrix(A)

Matrix([
[1, 4, 0,   4,  1],
[0, 1, 0,   0,  0],
[0, 0, 1, -10, -2],
[0, 0, 0,   1,  0],
[0, 0, 0,   0,  1]])